### ISSUE TITLE
PS2 Issues

### ISSUE THREAD

**Issue by RyWillo** [Kamshak/Pointshop2-Docs#1]
having some issues with PS2 on my server, the shop itself doesnt want to load, 

[ERROR] addons/pointshop2/lua/ps2/server/sv_pointshopcontroller.lua:122: attempt to compare number with string
1. s - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller.lua:122
2. succ - addons/libk/lua/libk/shared/1_sh_promises.lua:48
3. Done - addons/libk/lua/libk/shared/1_sh_promises.lua:116
4. Then - addons/libk/lua/libk/shared/1_sh_promises.lua:107
5. initializeInventory - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller.lua:121
6. unknown - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller.lua:313

[ERROR] addons/pointshop2/lua/ps2/server/sv_pointshopcontroller.lua:122: attempt to compare number with string
1. s - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller.lua:122
2. succ - addons/libk/lua/libk/shared/1_sh_promises.lua:48
1. Done - addons/libk/lua/libk/shared/1_sh_promises.lua:116
   1. Then - addons/libk/lua/libk/shared/1_sh_promises.lua:107
2. initializeInventory - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller.lua:121
   1. unknown - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller.lua:313
      Timer Failed! [Simple][@addons/pointshop2/lua/ps2/server/sv_pointshopcontroller.lua (line 312)]

**Comment by ValentinFunk** [comment]
Please open a ticket for any issues :) This one has been fixed
