### ISSUE TITLE
Poor documentation on wallet

### ISSUE THREAD

**Issue by BlackVoid** [Kamshak/Pointshop2-Docs#2]
The documentation on how to access a players wallet is poor and can't check how it's done in the code as I do not own Pointshop 2, however people are interested in Pointshop 2 support in my gamemode.

**Comment by ValentinFunk** [comment]
it's fairly simple, you just do ply.PS2_Wallet.points / ply.PS2_Wallet.premiumPoints.
If this is for a free addon let me know, i'll give you a free ps2 version

**Comment by BlackVoid** [comment]
It's for my public deathrun gamemode which can be found here: https://github.com/BlackVoid/deathrun
You can find my steam profile here: http://steamcommunity.com/id/theblackvoid

**Comment by ValentinFunk** [comment]
I have given you access to the script :)
