### ISSUE TITLE
NOT AN ISSUE JUST A REQUEST

### ISSUE THREAD

**Issue by chudders1231** [Kamshak/Pointshop2-Docs#4]
Hello,
I have read the documentation for the most part and cannot seem to find the info i need.
For pointshop 1, to detect whether pointshop was to use: if PS then.... Does PS2 work on the same method OR does it have an alternative?

Thanks,
Chad Masters

**Comment by ValentinFunk** [comment]
Sure, you can check for the Pointshop2 global

```
if Pointshop2 then 

end 
```
