### ISSUE TITLE
Importing from PS1 to PS2

### ISSUE THREAD

**Issue by chudders1231** [Kamshak/Pointshop2-Docs#5]
Hey,
Is there a native way to import from PS1 to PS2?

If not is it OK if i make a module to do so?

Thanks,
Chad Masters

**Comment by ValentinFunk** [comment]
Hey, there is currently no way to do it and due to the very different structure it will also be difficult to implement. If you want to give it a shot you can of course, there are no plans for an official version though.

**Comment by chudders1231** [comment]
Hey,
Do you have a way of detecting items and getting bits of info from it?

Thanks,
Chad Masters
